"""add ctfmenu_message

Revision ID: 56604a40e3a6
Revises: 6e2b6a2f8874
Create Date: 2026-07-01 19:37:24.915697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56604a40e3a6'
down_revision: Union[str, Sequence[str], None] = '6e2b6a2f8874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ctfmenu_message',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('extra_message', sa.String(), nullable=False),
    sa.CheckConstraint('id = 1', name='ctfmenu_message_only_one_row'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extra_message'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_ctfmenu_message_id'), 'ctfmenu_message', ['id'], unique=True)
    op.add_column(
        'config',
        sa.Column('ctfmenu_channel_id', sa.BigInteger(), nullable=True),
    )
    op.execute(
        "UPDATE config SET ctfmenu_channel_id = -1 "
        "WHERE ctfmenu_channel_id IS NULL"
    )
    op.alter_column('config', 'ctfmenu_channel_id', nullable=False)
    op.create_unique_constraint(
        'config_ctfmenu_channel_id_key',
        'config',
        ['ctfmenu_channel_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'config_ctfmenu_channel_id_key',
        'config',
        type_='unique',
    )
    op.drop_column('config', 'ctfmenu_channel_id')
    op.drop_index(op.f('ix_ctfmenu_message_id'), table_name='ctfmenu_message')
    op.drop_table('ctfmenu_message')
    # ### end Alembic commands ###
