"""initial schema

Revision ID: 6e2b6a2f8874
Revises: 
Create Date: 2026-07-01 19:32:37.471354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2b6a2f8874'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


LEGACY_SCHEMA = {
    "config": {
        "id",
        "announcement_channel_id",
        "ctf_channel_category_id",
        "archive_category_id",
        "pm_role_id",
        "member_role_id",
    },
    "events": {
        "id",
        "archived",
        "event_id",
        "title",
        "start",
        "finish",
        "channel_id",
        "scheduled_event_id",
        "locked_until",
        "locked_by",
    },
    "users": {
        "discord_id",
        "status",
        "skills",
        "rhythm_games",
    },
    "user_event": {
        "user_discord_id",
        "event_db_id",
    },
}


def legacy_schema_exists() -> bool:
    inspector = sa.inspect(op.get_bind())
    existing_tables = set(inspector.get_table_names())
    legacy_tables = set(LEGACY_SCHEMA)
    existing_legacy_tables = existing_tables & legacy_tables

    if not existing_legacy_tables:
        return False
    if existing_legacy_tables != legacy_tables:
        missing_tables = sorted(legacy_tables - existing_legacy_tables)
        raise RuntimeError(
            f"Cannot adopt incomplete legacy schema; missing tables: {missing_tables}"
        )

    for table_name, expected_columns in LEGACY_SCHEMA.items():
        existing_columns = {
            column["name"] for column in inspector.get_columns(table_name)
        }
        if existing_columns != expected_columns:
            raise RuntimeError(
                f"Cannot adopt incompatible legacy table: {table_name}"
            )

    return True


def upgrade() -> None:
    """Upgrade schema."""
    if legacy_schema_exists():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('announcement_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('ctf_channel_category_id', sa.BigInteger(), nullable=False),
    sa.Column('archive_category_id', sa.BigInteger(), nullable=False),
    sa.Column('pm_role_id', sa.BigInteger(), nullable=False),
    sa.Column('member_role_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('id = 1', name='config_only_one_row'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_channel_id'),
    sa.UniqueConstraint('archive_category_id'),
    sa.UniqueConstraint('ctf_channel_category_id'),
    sa.UniqueConstraint('member_role_id'),
    sa.UniqueConstraint('pm_role_id')
    )
    op.create_index(op.f('ix_config_id'), 'config', ['id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start', sa.BigInteger(), nullable=True),
    sa.Column('finish', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_event_id', sa.BigInteger(), nullable=True),
    sa.Column('locked_until', sa.BigInteger(), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('scheduled_event_id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.create_table('users',
    sa.Column('discord_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('status', sa.Enum('online', 'offline', name='enum_status'), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.Enum('web', 'reverse', 'pwn', 'crypto', 'misc', 'forensics', 'web3', 'Pentest', 'ppc', 'osint', 'hardware', 'network', name='enum_skills')), nullable=False),
    sa.Column('rhythm_games', sa.ARRAY(sa.Enum('pjsk', 'phigros', 'arcaea', 'osu', 'maimai', 'chunithm', 'sdvx', name='enum_rhythm_games')), nullable=False),
    sa.PrimaryKeyConstraint('discord_id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('user_event',
    sa.Column('user_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('event_db_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['event_db_id'], ['events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_discord_id'], ['users.discord_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_discord_id', 'event_db_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_event')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_config_id'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
